WARNING  cloud:test_file.py:111 断言类型[json_value]-->实际结果：{"success":false,"code":"04010314","message":"文件操作全部失败","data":{"batchFileResults":[{"srcFile":null,"rstFile":{"fileId":"63e9e4aad26da18944c743ed85e1c64f610fd5d0","parentFileId":null,"name":null,"description":null,"type":null,"fileExtension":null,"category":null,"createdAt":null,"updatedAt":null,"trashedAt":null,"localCreatedAt":null,"localUpdatedAt":null,"starred":null,"size":null,"userTags":null,"labels":null,"thumbnailUrls":null,"punishMode":null,"contentHash":null,"contentHashAlgorithm":null,"revisionId":null,"mediaMetaInfo":null,"addressDetail":null,"systemDir":null},"errCode":"04000101","message":"服务端下游请求返回失败"}]}} ；期望结果：{"code":"0000"} 不相符，断言失败