WARNING  cloud:test_file.py:111 断言类型[json_value]-->实际结果：{"success":false,"code":"04000000","message":"内部错误","data":null} ；期望结果：{"code":"0000"} 不相符，断言失败